name: Behaviour Bug or incompatibility
description: Report issues with incompatibilities or other behavior related issues
labels: [ 'triage', 'bug' ]
body:
  - type: textarea
    attributes:
      label: Expected behaviour
      description: What you expected to see.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Observed/Actual behavior
      description: What you actually saw
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps/models to reproduce
      description: This may include a build schematic, a video, or detailed instructions to help reconstruct the issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Plugin and Datapack list
      description: |
        All plugins and datapacks running on your server.
        To list plugins, run `/plugins`. For datapacks, run `/datapack list`.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Server version
      description: |
        Run `/version` on your server and **paste** the full, unmodified output here.
        "latest" is *not* a version; we require the output of `/version` so we can adequately track down the issue.
        Additionally, do NOT provide a screenshot, you MUST paste the entire output.
        <details>
        <summary>Example</summary>

        ```
        > version
        [20:34:42 INFO]: Checking version, please wait...
        [20:34:42 INFO]: This server is running Paper version 1.21-105-master@7e91a2c (2024-07-20T21:04:31Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
        [20:34:42 INFO]: You are running the latest version
        [20:34:42 INFO]: Previous version: 1.21-103-aa3b356 (MC: 1.21)
        ```

        </details>
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below.
        Th more information is provided, the quicker and more effective finding the solution to the issue is possible.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Before submitting this issue, please ensure the following:
        
        1. You are running the latest version of Celestial from the repository. The latest version can be found on [GitHub](https://github.com/Breezora/Celestial/releases).
        2. You searched for and ensured there isn't already an open issue regarding this.