name: Deploy to personal dev environment
concurrency: local development

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*

env:
  host_url: ${{ secrets.PTERODACTYL_HOST }}
  server_id: ${{ secrets.PTERODACTYL_SERVER_ID }}
  api_key: ${{ secrets.PTERODACTYL_API_KEY }}

jobs:
  stop_server:
    environment: local development
    runs-on: ubuntu-latest
    steps:
      - name: Stop local server
        run: |
          curl "${{ env.host_url }}/api/client/servers/${{ env.server_id }}/power" \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer ${{ env.api_key }}' \
          -X POST \
          -d '{"signal":"stop"}'

  deploy:
    environment: local development
    runs-on: ubuntu-latest
    needs:
      - stop_server
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 22
          distribution: temurin
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build project
        run: ./gradlew buildNeeded -x test

      - name: Upload artifact into personal dev environment
        uses: rexlManu/pterodactyl-upload-action@v2.4
        with:
          panel-host: ${{ env.host_url }}
          api-key: ${{ env.api_key }}
          server-id: ${{ env.server_id }}
          source: build/libs/*-deploy.jar
          target: /plugins/
          restart: true

  start_server:
    environment: local development
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - name: Start local server
        run: |
          curl "${{ env.host_url }}/api/client/servers/${{ env.server_id }}/power" \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer ${{ env.api_key }}' \
          -X POST \
          -d '{"signal":"start"}'