name: Update Jira time tracking
on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*

jobs:
  update_jira-time:
    if: "!startsWith(github.event.head_commit.message, 'Merge')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get all commit messages
        id: commit_messages
        run: |
          COMMIT_MSGS=$(git log --pretty=%B ${{ github.event.before }}..${{ github.event.after }} || tr '\n' ' ') 
          echo "messages=$COMMIT_MSGS" >> $GITHUB_ENV

      - name: Extract time from commit messages and sum
        id: extract_time
        run: |
          echo "Commit messages: ${{ env.messages }}"
          
          HOURS=$(echo "${{ env.messages }}" | grep -oP '\d+(?=\s*hour(s)?)' | awk '{sum+=$1} END {print sum+0}')
          MINUTES=$(echo "${{ env.messages }}" | grep -oP '\d+(?=\s*min(ute)?s?)' | awk '{sum+=$1} END {print sum+0}')
          SECONDS=$(echo "${{ env.messages }}" | grep -oP '\d+(?=\s*second(s)?)' | awk '{sum+=$1} END {print sum+0}')
          
          TOTAL_SECONDS=$((HOURS * 3600 + MINUTES * 60 + SECONDS))
          
          echo "Extracted time: ${TOTAL_SECONDS}s (${HOURS}h ${MINUTES}m ${SECONDS}s)"
          echo "total_time=${TOTAL_SECONDS}" >> $GITHUB_ENV

      - name: Extract Jira issue key
        id: extract_issue_key
        run: |
          ISSUE_KEY=$(echo "${{ env.messages }}" | grep -oE '[A-Z]+-[0-9]+' | head -n 1)
          if [ -z "$ISSUE_KEY" ]; then
            echo "No Jira issue key found in commit message. Skipping."
            exit 0
          fi
          echo "Jira Issue Key: $ISSUE_KEY"
          echo "issue_key=$ISSUE_KEY" >> $GITHUB_ENV

      - name: Add worklog to Jira
        run: |
          curl --request POST \
            --url "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ env.issue_key }}/worklog" \
            --user "${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --data "{ \"timeSpentSeconds\": \"${{ env.total_time }}\" }"